### ISSUE TITLE
неправильно выполнено FR006

### ISSUE THREAD

**Issue by zaverden** [Zulcom/ikit-mita-hw2#1]
FR006 Вывести номер машины Вольдемара

Это означает, что надо начинать цепочку свойств от Вольдемара, а не от `lada`. Может случиться, что ты неправильно написал код, и в итоге `voldemar` и `lada` вообще не связались.

**Comment by Zulcom** [comment]
Fixed in commit d3f1be6cbcfe6c2f36c2db02427962034dd34e2f
